# Generated by Django 4.2.7 on 2025-11-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_prob_diff_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_prob_accept_rate_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_prob_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_prob_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_prob_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='problemdiscussion',
            name='problems_disc_prob_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='problemdiscussion',
            name='problems_disc_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='problemdiscussion',
            name='problems_disc_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='problemdiscussion',
            name='problems_disc_solution_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problems_sub_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problems_sub_prob_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problems_sub_user_prob_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problems_sub_status_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='problems_sub_judged_idx',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='problems_test_prob_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='problems_test_prob_hidden_idx',
        ),
    ]
