# Generated by Django 4.2.7 on 2025-11-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_problems_prob_diff_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='examples',
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='Complete problem description including constraints, examples, input/output format'),
        ),
    ]
