# Generated by Django 4.2.7 on 2025-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_remove_problem_constraints_remove_problem_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='Problem constraints (one per line)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='Problem description, examples, input/output format'),
        ),
    ]
