# Generated by Django 4.2.7 on 2025-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cointransaction',
            name='users_coin_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='cointransaction',
            name='users_coin_type_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_xp_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_prob_solved_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_curr_streak_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_last_activity_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='userachievement',
            name='users_achv_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='userachievement',
            name='users_achv_type_idx',
        ),
    ]
