# Generated by Django 4.2.7 on 2025-11-09 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0004_remove_problem_problems_prob_diff_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('bonus_coins', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_xp', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('participants_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='problems.problem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StreakFreezeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Streak Freeze', max_length=100)),
                ('description', models.TextField(default='Protects your streak for one day if you miss a challenge')),
                ('cost_in_coins', models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(1)])),
                ('icon', models.CharField(default='❄️', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Streak Freeze Item',
                'verbose_name_plural': 'Streak Freeze Items',
            },
        ),
        migrations.CreateModel(
            name='StreakStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_challenges_completed', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('streak_freeze_count', models.IntegerField(default=0, help_text='Number of streak freeze items owned')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Streak stats',
            },
        ),
        migrations.CreateModel(
            name='StreakFreezePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_challenges.streakfreezeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freeze_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('coins_earned', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='daily_challenges.dailychallenge')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problems.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='daily_chall_user_id_24dc06_idx')],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('time_taken', models.DurationField()),
                ('completed_at', models.DateTimeField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='daily_challenges.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['challenge', 'rank'],
                'indexes': [models.Index(fields=['challenge', 'rank'], name='daily_chall_challen_280f26_idx')],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['-date'], name='daily_chall_date_592f80_idx'),
        ),
    ]
