# Generated by Django 4.2.7 on 2025-11-09 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('achievement_type', models.CharField(max_length=50)),
                ('requirement_description', models.TextField()),
                ('coin_reward', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('max_completions', models.IntegerField(blank=True, help_text='Max times this can be completed', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('legendary', 'Legendary')], default='bronze', max_length=20)),
                ('badge_type', models.CharField(choices=[('problem_solving', 'Problem Solving'), ('streak', 'Streak'), ('contest', 'Contest'), ('battle', 'Battle'), ('social', 'Social'), ('special', 'Special')], max_length=30)),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=100)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('image_url', models.URLField(blank=True, help_text='Optional badge image URL')),
                ('requirement_type', models.CharField(help_text='Type of requirement (e.g., problems_solved, streak_days)', max_length=50)),
                ('requirement_value', models.IntegerField(help_text='Value needed to unlock (e.g., 100 for 100 problems)')),
                ('requirement_description', models.TextField(help_text='Human-readable requirement')),
                ('coin_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_reward', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_secret', models.BooleanField(default=False, help_text='Hidden until unlocked')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BadgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏅', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Badge categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('milestone_type', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('coin_reward', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('special_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='achievements.badge')),
            ],
            options={
                'ordering': ['milestone_type', 'threshold'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='achievements.badgecategory'),
        ),
        migrations.CreateModel(
            name='UserMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('value_achieved', models.IntegerField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_milestones', to='achievements.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress towards next tier')),
                ('is_displayed', models.BooleanField(default=False, help_text='Display on profile')),
                ('is_new', models.BooleanField(default=True, help_text="Show 'NEW' indicator")),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='achievements.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='achievement_user_id_d7ca0a_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completion_count', models.IntegerField(default=1, help_text='Number of times completed')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='achievement_user_id_13f95c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(default=0)),
                ('target_value', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracking', to='achievements.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Badge progress',
                'indexes': [models.Index(fields=['user', 'badge'], name='achievement_user_id_dcdccb_idx')],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'is_active'], name='achievement_badge_t_87ab1e_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['tier'], name='achievement_tier_bda883_idx'),
        ),
    ]
