# Generated by Django 4.2.7 on 2025-11-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_msg_chat_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_msg_sender_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_msg_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='core_contact_status_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notif_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notif_user_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notif_type_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='core_chat_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='core_chat_admin_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='core_chat_status_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='core_chat_cat_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportchat',
            name='core_chat_last_activity_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemlog',
            name='core_log_level_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemlog',
            name='core_log_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='core_activity_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='core_activity_type_time_idx',
        ),
    ]
