# Generated by Django 4.2.7 on 2025-11-09 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0004_remove_problem_problems_prob_diff_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('friend', 'Friend Challenge'), ('random', 'Random Match')], max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Opponent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('stake', models.IntegerField(default=50, help_text='MateCoins at stake', validators=[django.core.validators.MinValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=30, help_text='Time limit in minutes')),
                ('spectator_count', models.IntegerField(default=0)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_initiated', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_received', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='problems.problem')),
                ('spectators', models.ManyToManyField(blank=True, related_name='watching_battles', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_battles', models.IntegerField(default=0)),
                ('battles_won', models.IntegerField(default=0)),
                ('battles_lost', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('best_win_streak', models.IntegerField(default=0)),
                ('total_coins_won', models.IntegerField(default=0)),
                ('total_coins_lost', models.IntegerField(default=0)),
                ('fastest_solve', models.DurationField(blank=True, help_text='Fastest problem solve in battle', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Battle stats',
            },
        ),
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('battle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battles.battle')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_invitations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DurationField(help_text='Time taken from battle start')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_submissions', to='battles.battle')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='problems.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('battle', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', '-created_at'], name='battles_bat_status_81aea0_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['challenger', '-created_at'], name='battles_bat_challen_ed8578_idx'),
        ),
    ]
