# Generated by Django 4.2.7 on 2025-06-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_type', models.CharField(choices=[('judge0', 'Judge0 API'), ('docker', 'Docker Sandbox'), ('custom', 'Custom Judge')], default='judge0', max_length=20)),
                ('api_url', models.URLField(blank=True, help_text='Judge API URL')),
                ('api_key', models.CharField(blank=True, help_text='API key for judge service', max_length=200)),
                ('default_time_limit', models.FloatField(default=1.0, help_text='Default time limit in seconds')),
                ('default_memory_limit', models.IntegerField(default=128, help_text='Default memory limit in MB')),
                ('max_time_limit', models.FloatField(default=10.0, help_text='Maximum allowed time limit')),
                ('max_memory_limit', models.IntegerField(default=512, help_text='Maximum allowed memory limit')),
                ('enable_compilation', models.BooleanField(default=True)),
                ('enable_runtime', models.BooleanField(default=True)),
                ('enable_sandbox', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Judge Configuration',
                'verbose_name_plural': 'Judge Configurations',
            },
        ),
        migrations.CreateModel(
            name='JudgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(help_text='Judge0 submission ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(default=list, help_text='Test case results from judge')),
                ('compilation_output', models.TextField(blank=True)),
                ('execution_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C'), ('csharp', 'C#'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('kotlin', 'Kotlin')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('file_extension', models.CharField(max_length=10)),
                ('judge0_id', models.IntegerField(help_text='Judge0 language ID')),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit_multiplier', models.FloatField(default=1.0, help_text='Time limit multiplier for this language')),
                ('memory_limit_multiplier', models.FloatField(default=1.0, help_text='Memory limit multiplier for this language')),
                ('template_code', models.TextField(blank=True, help_text='Default template code for this language')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Test case result status', max_length=50)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory used in MB', null=True)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('actual_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='judge.judgesubmission')),
            ],
            options={
                'ordering': ['test_case__order'],
            },
        ),
    ]
