# Generated by Django 4.2.7 on 2025-06-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.testcase'),
        ),
        migrations.AddField(
            model_name='judgesubmission',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_submission', to='problems.submission'),
        ),
        migrations.AddField(
            model_name='judgelog',
            name='judge_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.judgesubmission'),
        ),
        migrations.AddField(
            model_name='judgelog',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='testcaseresult',
            unique_together={('judge_submission', 'test_case')},
        ),
    ]
