# Generated by Django 4.2.7 on 2025-11-09 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0004_remove_problem_problems_prob_diff_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('banner_url', models.URLField(blank=True)),
                ('icon', models.CharField(default='📚', max_length=100)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('estimated_duration', models.IntegerField(help_text='Estimated hours to complete')),
                ('completion_reward_coins', models.IntegerField(default=500)),
                ('completion_reward_xp', models.IntegerField(default=1000)),
                ('certificate_awarded', models.BooleanField(default=True)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-enrolled_count'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_optional', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PathModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('video_url', models.URLField(blank=True)),
                ('reading_material', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Requires previous modules to be completed')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning_paths.learningpath')),
                ('problems', models.ManyToManyField(related_name='path_modules', through='learning_paths.ModuleProblem', to='problems.problem')),
            ],
            options={
                'ordering': ['learning_path', 'order'],
                'unique_together': {('learning_path', 'order')},
            },
        ),
        migrations.AddField(
            model_name='moduleproblem',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_paths.pathmodule'),
        ),
        migrations.AddField(
            model_name='moduleproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='topics',
            field=models.ManyToManyField(related_name='learning_paths', to='learning_paths.topic'),
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intuition', models.TextField(help_text='High-level approach')),
                ('approach', models.TextField(help_text='Detailed explanation')),
                ('complexity_analysis', models.TextField(help_text='Time and space complexity')),
                ('code_walkthrough', models.TextField(help_text='Line-by-line explanation')),
                ('video_url', models.URLField(blank=True)),
                ('video_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('example_code', models.JSONField(default=dict, help_text='Code examples in different languages')),
                ('views', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_official', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorials', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_editorials', to=settings.AUTH_USER_MODEL)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='problems.problem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learning_paths.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('learning_path', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_modules', models.ManyToManyField(blank=True, related_name='completed_by', to='learning_paths.pathmodule')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='learning_paths.pathmodule')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning_paths.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='learning_pa_user_id_f3bda7_idx')],
                'unique_together': {('user', 'learning_path')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='moduleproblem',
            unique_together={('module', 'problem')},
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['is_published', '-enrolled_count'], name='learning_pa_is_publ_6b710d_idx'),
        ),
    ]
