# Generated by Django 4.2.7 on 2025-11-09 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_paths', '0001_initial'),
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('required_problems_solved', models.IntegerField(default=0)),
                ('required_contests_participated', models.IntegerField(default=0)),
                ('badge_icon', models.CharField(default='🏆', max_length=50)),
                ('badge_color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='learning_paths.learningpath')),
            ],
            options={
                'ordering': ['difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=200)),
                ('shared_on_linkedin', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to='certifications.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['user', '-earned_at'], name='certificati_user_id_e533b4_idx'), models.Index(fields=['certificate_id'], name='certificati_certifi_63d264_idx')],
                'unique_together': {('certification', 'user')},
            },
        ),
    ]
