# Generated by Django 4.2.7 on 2025-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_scanner', '0002_add_analysis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumescan',
            name='ats_score',
            field=models.FloatField(default=0.0, help_text='ATS compatibility score'),
        ),
        migrations.AlterField(
            model_name='resumescan',
            name='keyword_score',
            field=models.FloatField(default=0.0, help_text='Keyword match score'),
        ),
        migrations.AlterField(
            model_name='resumescan',
            name='report',
            field=models.TextField(blank=True, help_text='Detailed analysis report'),
        ),
        migrations.AlterField(
            model_name='resumescan',
            name='suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Improvement suggestions'),
        ),
    ]
